### ISSUE TITLE
how to hide GpioPad=****

### ISSUE THREAD

**Issue by MalsonQu** [jqqqqqqqqqq/Hackintosh-HP-Z2-Mini-G4#2]
when boot up will show GpioPad=**** on screen and i was remove boot-args option -v, what should i do to hide it

**Comment by MalsonQu** [comment]
my computer

**Comment by MalsonQu** [comment]
my computer

**Comment by MalsonQu** [comment]
my compuer
i7-8700
64GB
WX 4150 (disabled iGPU)
mojave 10.14.6

**Comment by jqqqqqqqqqq** [comment]
IDK, this is something I will not try to solve. 
Also having this screen. Probably you can ask owner of thunderboltpkg.
If you don't have the thunderbolt flex io card, this is easy. Remove thunderbolt related SSDTs, patches and tbtforcepwr.efi

**Comment by MalsonQu** [comment]
got it thank you
